### ISSUE TITLE
Dovecot config ssl config in wrong place

### ISSUE THREAD

**Issue by kirrus** [BigRedS/postfixadmin-installer#27]
Dovecot refuses to start because:
doveconf: Fatal: Error in configuration file /etc/dovecot/dovecot.conf: ssl enabled, but ssl_cert not set

Needs:
 ssl_cert=</etc/ssl/certs/ssl-cert-snakeoil.pem
 ssl_key=</etc/ssl/private/ssl-cert-snakeoil.key
not in a protocol section

**Comment by jpptinsley** [comment]
This one's fixed
